name: npm publish

on:
  pull_request:
    branches:
      - master
    paths:
      - package.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout source code
        uses: actions/checkout@v2

      - name: â” Setup nodejs
        uses: actions/setup-node@v1.4.3
        with:
          node-version: lts/* # ìµœì‹  ì¥ê¸°ì§€ì›(LTS) ë²„ì „ ì¶”ì²œ
          registry-url: https://registry.npmjs.org/

      - name: ğŸ“¦ Install dependencies
        run: npm ci # npm installë³´ë‹¤ ciê°€ ë” ê¹”ë”

      - name: ğŸ— Build project
        run: npm run build

      - name: ğŸš€ Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: ğŸ“¤ Notification
        uses: 8398a7/action-slack@v2.6.0
        with:
          status: ${{ job.status }}
          author_name: Github Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
